- name: set variables
  variables:
    password: qwerty

- name: create and populate table
  steps:
    - name: create table
      db:
        dbQuery: >
          create table if not exists t1 (id text, deleted_at timestamp);
    - name: populate with data
      db:
        dbQuery: >
          insert into t1(id, deleted_at) values ('q', now());
    - name: get count
      dbQuery: >
        select count(*) as cnt from t1;
      variables_to_set:
        cnt: '0.cnt'
    - name: get count 2
      db:
        dbQuery: >
          select count(*) as cnt from t1;
        variables_to_set:
          cnt2: '0.cnt'

- name: show count plain
  echo_message: '{{$cnt}}'

- name: show count
  echo:
    message: '{{$cnt2}}'

- name: drop table
  dbQuery: >
    drop table t1;
