- variables:
    name: Tom
    path: tom

- name: check request
  method: GET
  path: /{{$path}}
  responseStatus: 200
  response: |
    {"age": 28,"name":"{{$name}}", "items":[1, 2, 4, 3]}
  comparisonParams:
    ignoreArraysOrdering: true
