name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.20'
    
    - name: Run tests
      run: go test -v ./...
    
    - name: Build binaries
      run: |
        # Build for multiple platforms
        GOOS=linux GOARCH=amd64 go build -o dist/declarate-linux-amd64 ./cmd/example/
        GOOS=linux GOARCH=arm64 go build -o dist/declarate-linux-arm64 ./cmd/example/
        GOOS=darwin GOARCH=amd64 go build -o dist/declarate-darwin-amd64 ./cmd/example/
        GOOS=darwin GOARCH=arm64 go build -o dist/declarate-darwin-arm64 ./cmd/example/
        GOOS=windows GOARCH=amd64 go build -o dist/declarate-windows-amd64.exe ./cmd/example/
    
    - name: Generate changelog
      id: changelog
      run: |
        # Simple changelog generation (you can replace with better tools like git-chglog)
        echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
        git log --pretty=format:"- %s" $(git describe --tags --abbrev=0 HEAD^)..HEAD >> $GITHUB_OUTPUT
        echo "" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        body: |
          ## Changes in this release
          ${{ steps.changelog.outputs.CHANGELOG }}
          
          ## Installation
          Download the appropriate binary for your platform from the assets below.
          
          ### Linux/macOS
          ```bash
          chmod +x declarate-*
          sudo mv declarate-* /usr/local/bin/declarate
          ```
          
          ### Windows
          Download `declarate-windows-amd64.exe` and add it to your PATH.
        files: |
          dist/*
        draft: false
        prerelease: false
